# RPM spec file for pgEdge Natural Language Agent
# Builds from tarballs generated by GoReleaser
%global sname   pgedge-nla
Name:           %{sname}
Version:        %{pgedge_nla_version}
Release:        %{pgedge_nla_buildnum}%{?dist}
Summary:        pgEdge Natural Language Agent - PostgreSQL MCP Server and Clients
License:        PostgreSQL License
URL:            https://github.com/pgEdge/pgedge-postgres-mcp
Source0:        pgedge-postgres-mcp-server_%{version}_linux_%{arch}.tar.gz
Source1:        pgedge-postgres-mcp-cli_%{version}_linux_%{arch}.tar.gz
Source2:        pgedge-nla-web_%{version}_noarch.tar.gz
Source4:        pgedge-postgres-mcp.service
Source5:        postgres-mcp.yaml
Source6:        postgres-mcp.env
Source7:        nla-cli.yaml
Source8:        pgedge-nla-web.nginx
BuildArch:      %{_arch}

%description
pgEdge Natural Language Agent provides a Model Context Protocol (MCP) server
for PostgreSQL databases, along with command-line and web-based chat clients.
It enables natural language interaction with PostgreSQL databases through
various LLM providers (Anthropic, OpenAI, Ollama).

# ============================================================================
# Server Package (renamed to pgedge-postgres-mcp)
# ============================================================================
%package -n pgedge-postgres-mcp
Summary:        pgEdge MCP Server for PostgreSQL

%description -n pgedge-postgres-mcp
Model Context Protocol (MCP) server that enables natural language
queries against PostgreSQL databases. Provides HTTP/HTTPS API with read-only
query execution, schema analysis, and semantic search capabilities.

# ============================================================================
# CLI Package
# ============================================================================
%package cli
Summary:        pgEdge Natural Language Agent - CLI Client
Requires:       pgedge-postgres-mcp = %{version}-%{release}

%description cli
Command-line chat client for interacting with PostgreSQL databases
using natural language. Connects to Natural Language Agent and supports
multiple LLM providers (Anthropic Claude, OpenAI, Ollama).

# ============================================================================
# Web Package
# ============================================================================
%package web
Summary:        pgEdge Natural Language Agent - Web UI
Requires:       pgedge-postgres-mcp = %{version}-%{release}
Requires:       python3 nginx
BuildArch:      noarch

%description web
Modern React-based web interface for the pgEdge Natural Language
Agent. Provides an intuitive UI for natural language database queries,
monitoring, and administration.

# ============================================================================
# Build Section
# ============================================================================
%prep
# Extract all source tarballs
mkdir -p %{_builddir}/server %{_builddir}/cli %{_builddir}/web
tar -xzf %{SOURCE0} -C %{_builddir}/server
tar -xzf %{SOURCE1} -C %{_builddir}/cli
tar -xzf %{SOURCE2} -C %{_builddir}/web

%pre -n pgedge-postgres-mcp
# Ensure pgedge user/group exists
getent group pgedge >/dev/null || groupadd -r pgedge
getent passwd pgedge >/dev/null || \
    useradd -r -g pgedge -d /var/lib/pgedge -s /sbin/nologin \
    -c "pgEdge Services" pgedge
exit 0

%build
syft dir:%{_builddir}/server -o cyclonedx-json > %{_builddir}/pgedge-postgres-mcp-sbom.json || exit 1
KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5}' | head -n 1); export KEY_ID
gpg --armor --detach-sign --output %{_builddir}/pgedge-postgres-mcp-sbom.json.asc %{_builddir}/pgedge-postgres-mcp-sbom.json || exit 1

syft dir:%{_builddir}/cli -o cyclonedx-json > %{_builddir}/%{sname}-cli-sbom.json || exit 1
KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5}' | head -n 1); export KEY_ID
gpg --armor --detach-sign --output %{_builddir}/%{sname}-cli-sbom.json.asc %{_builddir}/%{sname}-cli-sbom.json || exit 1

syft dir:%{_builddir}/web -o cyclonedx-json > %{_builddir}/%{sname}-web-sbom.json || exit 1
KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5}' | head -n 1); export KEY_ID
gpg --armor --detach-sign --output %{_builddir}/%{sname}-web-sbom.json.asc %{_builddir}/%{sname}-web-sbom.json || exit 1

%install
# Create directory structure
install -d %{buildroot}%{_bindir}
install -d %{buildroot}%{_datadir}/pgedge-nla/examples
install -d %{buildroot}%{_datadir}/pgedge-nla/web
install -d %{buildroot}%{_sysconfdir}/pgedge
install -d %{buildroot}%{_defaultdocdir}/pgedge-postgres-mcp
install -d %{buildroot}%{_defaultdocdir}/pgedge-nla-cli
install -d %{buildroot}%{_defaultdocdir}/pgedge-nla-web

# Install server
install -m 755 %{_builddir}/server/pgedge-postgres-mcp %{buildroot}%{_bindir}/
install -m 644 %{_builddir}/server/LICENSE.md %{buildroot}%{_defaultdocdir}/pgedge-postgres-mcp/
install -m 644 %{_builddir}/server/README.md %{buildroot}%{_defaultdocdir}/pgedge-postgres-mcp/

mkdir -p %{buildroot}%{_datadir}
install -p -m 0644 %{_builddir}/pgedge-postgres-mcp-sbom.json %{buildroot}%{_datadir}/pgedge-postgres-mcp-sbom.json
install -p -m 0644 %{_builddir}/pgedge-postgres-mcp-sbom.json.asc %{buildroot}%{_datadir}/pgedge-postgres-mcp-sbom.json.asc

# Install systemd service
install -d %{buildroot}%{_unitdir}
install -m 644 %{SOURCE4} %{buildroot}%{_unitdir}/pgedge-postgres-mcp.service

# Create required directories
install -d %{buildroot}/var/lib/pgedge/postgres-mcp
install -d %{buildroot}/var/log/pgedge/postgres-mcp
install -m 644 %{SOURCE5} %{buildroot}%{_sysconfdir}/pgedge/postgres-mcp.yaml
install -m 644 %{SOURCE6} %{buildroot}%{_sysconfdir}/pgedge/postgres-mcp.env

# Install CLI
install -m 755 %{_builddir}/cli/pgedge-nla-cli %{buildroot}%{_bindir}/
install -m 644 %{_builddir}/cli/LICENSE.md %{buildroot}%{_defaultdocdir}/pgedge-nla-cli/
install -m 644 %{_builddir}/cli/README.md %{buildroot}%{_defaultdocdir}/pgedge-nla-cli/
install -p -m 0644 %{_builddir}/%{sname}-cli-sbom.json %{buildroot}%{_datadir}/%{sname}-cli-sbom.json
install -p -m 0644 %{_builddir}/%{sname}-cli-sbom.json.asc %{buildroot}%{_datadir}/%{sname}-cli-sbom.json.asc
install -m 644 %{SOURCE7} %{buildroot}%{_sysconfdir}/pgedge/nla-cli.yaml
install -d -m 0755 %{buildroot}/etc/skel/.config/pgedge

# Install Web UI
install -m 644 %{_builddir}/web/LICENSE.md %{buildroot}%{_defaultdocdir}/pgedge-nla-web/
install -m 644 %{_builddir}/web/README.md %{buildroot}%{_defaultdocdir}/pgedge-nla-web
install -d %{buildroot}%{_datadir}/pgedge/nla-web
install -d %{buildroot}/var/log/pgedge/nla-web
cp -r %{_builddir}/web/dist/* %{buildroot}%{_datadir}/pgedge/nla-web/
install -d %{buildroot}/etc/nginx/conf.d
install -m 644 %{SOURCE8} %{buildroot}/etc/nginx/conf.d/pgedge-nla-web.conf
install -p -m 0644 %{_builddir}/%{sname}-web-sbom.json %{buildroot}%{_datadir}/%{sname}-web-sbom.json
install -p -m 0644 %{_builddir}/%{sname}-web-sbom.json.asc %{buildroot}%{_datadir}/%{sname}-web-sbom.json.asc

# Note: the kb.db knowledgebase and the kb-builder tool are no longer shipped
# here. The knowledgebase ships in the standalone pgedge-ai-kb package, and the
# builder binary (renamed pgedge-ai-kb-builder) is released from pgedge-ai-kb.

%files -n pgedge-postgres-mcp
%license %{_defaultdocdir}/pgedge-postgres-mcp/LICENSE.md
%doc %{_defaultdocdir}/pgedge-postgres-mcp/README.md
%{_bindir}/pgedge-postgres-mcp
%config(noreplace) %{_sysconfdir}/pgedge/postgres-mcp.yaml
%config(noreplace) %{_sysconfdir}/pgedge/postgres-mcp.env
%{_datadir}/pgedge-postgres-mcp-sbom.json
%{_datadir}/pgedge-postgres-mcp-sbom.json.asc
%{_unitdir}/pgedge-postgres-mcp.service
%dir %attr(0755,pgedge,pgedge) /var/lib/pgedge
%dir %attr(0755,pgedge,pgedge) /var/lib/pgedge/postgres-mcp
%dir %attr(0755,pgedge,pgedge) /var/log/pgedge
%dir %attr(0755,pgedge,pgedge) /var/log/pgedge/postgres-mcp

%files cli
%license %{_defaultdocdir}/pgedge-nla-cli/LICENSE.md
%doc %{_defaultdocdir}/pgedge-nla-cli/README.md
%{_bindir}/pgedge-nla-cli
%config(noreplace) %{_sysconfdir}/pgedge/nla-cli.yaml
%dir %attr(0755,root,root) /etc/skel/.config
%dir %attr(0755,root,root) /etc/skel/.config/pgedge
%{_datadir}/%{sname}-cli-sbom.json
%{_datadir}/%{sname}-cli-sbom.json.asc

%files web
%license %{_defaultdocdir}/pgedge-nla-web/LICENSE.md
%doc %{_defaultdocdir}/pgedge-nla-web/README.md
%dir %attr(0755,pgedge,pgedge) /var/log/pgedge
%dir %attr(0755,pgedge,pgedge) /var/log/pgedge/nla-web
%{_datadir}/pgedge/nla-web
%config(noreplace) /etc/nginx/conf.d/pgedge-nla-web.conf
%{_datadir}/%{sname}-web-sbom.json
%{_datadir}/%{sname}-web-sbom.json.asc

%post -n pgedge-postgres-mcp
%systemd_post pgedge-postgres-mcp.service

%preun -n pgedge-postgres-mcp
%systemd_preun pgedge-postgres-mcp.service

%postun -n pgedge-postgres-mcp
%systemd_postun_with_restart pgedge-postgres-mcp.service

%post web
if [ $1 -eq 1 ]; then
    # Test nginx config and reload if valid
    nginx -t >/dev/null 2>&1 && systemctl reload nginx >/dev/null 2>&1 || :
fi

%preun web
if [ $1 -eq 0 ]; then
    # Reload nginx after config removal
    systemctl reload nginx >/dev/null 2>&1 || :
fi

%clean
rm -rf %{buildroot}

%changelog
* Mon Jun 15 2026 pgEdge Team <support@pgedge.com> - 1.0.0
- Move packaging in-repo (built from this repo's release.yml).
- Drop the kb-builder binary and its config/SBOM; the builder now ships from
  the standalone pgedge-ai-kb project. Server, CLI and Web packages unchanged.
* Tue Jun 02 2026 pgEdge Team <support@pgedge.com> - 1.0.0
- Drop the pgedge-postgres-mcp-kb subpackage; the kb.db knowledgebase now
  ships in the standalone pgedge-ai-kb package at a new path
  (/usr/share/pgedge/pgedge-ai-kb/kb.db).
* Fri Mar 27 2026 pgEdge Team <support@pgedge.com> - 1.0.0
- Update RPM packages of MCP server, CLI, web and KB
* Fri Jan 23 2026 pgEdge Team <support@pgedge.com> - 1.0.0-beta3
- Update RPM packages of MCP server, CLI, web and KB
* Wed Jan 14 2026 pgEdge Team <support@pgedge.com> - 1.0.0-beta2
- Update RPM packages of MCP server, CLI, web and KB
* Mon Dec 15 2025 pgEdge Team <support@pgedge.com> - 1.0.0-beta1
- Initial RPM package
- Server: MCP server for PostgreSQL (pgedge-postgres-mcp)
- CLI: Command-line chat client (pgedge-nla-cli)
- Web: Web-based chat interface (pgedge-nla-web)
