name: CI - Documentation

on:
    push:
        branches: [ main, develop, 'feat/llm-lib-*' ]
    pull_request:
        branches: [ main, develop, 'feat/llm-lib-*' ]
    workflow_dispatch:

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    docs:
        name: Documentation
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

            - name: Set up Python
              uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
              with:
                  python-version: '3.11'
                  cache: 'pip'

            - name: Create virtual environment
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt

            - name: Build documentation
              run: |
                  source venv/bin/activate
                  mkdocs build -v

            - name: Upload documentation artifact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
              with:
                  if-no-files-found: error
                  name: pgedge-docs-site
                  path: site
                  retention-days: 7
